"""add transfer fields to transactions

Revision ID: 051811ee099b
Revises: 
Create Date: 2026-06-04 23:39:46.722580

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '051811ee099b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('is_transfer', sa.Boolean(), nullable=False))
    op.add_column('transactions', sa.Column('transfer_pair_id', sa.Uuid(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transactions', 'transfer_pair_id')
    op.drop_column('transactions', 'is_transfer')
    # ### end Alembic commands ###
